### ISSUE TITLE
Seems to be not worth in real project.

### ISSUE THREAD

**Issue by huanghe810229530** [RuiAAPeres/Reactor#19]
With the price of this structure is too big, need to abandon Alamofire etc. Many excellent library?

**Comment by RuiAAPeres** [comment]
I'm not sure what's being asked here, so I will take a stab at what you mean:

Reactor has a very particular use case, that will not suit everyone. It allows you to not repeat yourself in terms of your application flow, particularly how your model layer works:

<img width="627" alt="screen shot 2016-05-27 at 14 28 07" src="https://cloud.githubusercontent.com/assets/949286/15609303/25a97d22-2417-11e6-8dcd-1e2c467a0781.png">

Saying that Alamofire needs to be abandoned in order to use it, is a bit unfair, since you only need to make Alamofire comply with the [`Connection`](https://github.com/MailOnline/Reactor/blob/master/Reactor/Core/Network/Connection.swift#L17#L31) protocol. 

As for other libraries, I think you are referring to parsing and persistence. The persistence, doesn't have a protocol yet, but it can easily be created ( I will work on that). As for the parser you can use the [`Mappable`](https://github.com/MailOnline/Reactor/blob/master/Reactor/Core/Parser/Mappable.swift#L24#L33). 

Hope this can make you change your mind about Reactor and how useful it can be. 🦄 In the meantime, I will update the documentation, so I can clarify this for other potential users.

**Comment by huanghe810229530** [comment]
I think I understand is wrong, I'm looking forward to can be used to project. Thank you!

**Comment by RuiAAPeres** [comment]
@huanghe810229530 I just updated the README. The [3rd Party section](https://github.com/MailOnline/Reactor#using-3rd-party-dependencies), should be useful.

**Comment by huanghe810229530** [comment]
@RuiAAPeres I am new to ReactiveCocoa, of course, this update to help to me.Thank you very much!
